version: "3.8"

services:
  northwind_data_neo4j_etl:
    build:
      context: .
      dockerfile: ./ETL_pipelines/Dockerfile
    env_file:
      - .env

  neo4j:
    image: neo4j:5.14
    container_name: graph-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.meta.data
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: